package Thunderhorse::Router::Location;

use v5.40;
use Mooish::Base -standard;

use Future::AsyncAwait;
use Gears::X;

extends 'Gears::Router::Location::SigilMatch';

has param 'method' => (
	isa => Str,
	default => 'GET',
);

has param 'name' => (
	isa => Str,
	lazy => 1,
);

has param 'to' => (
	isa => Str | CodeRef,
);

has param 'order' => (
	isa => Int,
	default => 0,
);

has param 'pagi' => (
	isa => Bool,
	default => false,
);

has param 'controller' => (
	isa => ConsumerOf ['Thunderhorse::Routable'],
);

sub BUILD ($self, $)
{
	Gears::X->raise('controller has no action ' . $self->to)
		unless $self->get_destination;

	# build name eagerly
	$self->name;
}

sub _build_name ($self)
{
	my $method = $self->method;
	my $pattern = $self->pattern;
	my $id = $self->router->get_next_route_id;

	# autogenerated location name should be readable, but unique
	return "_${method}_${pattern}_${id}";
}

sub get_destination ($self)
{
	return $self->to if $self->pagi;
	return $self->controller->can($self->to);
}

# TODO: cache this
# TODO: move this somewhere else (but not to match)
sub pagify ($self, $matched)
{
	if ($self->pagi) {
		# TODO: this should always mark as rendered
		# TODO: adjust PAGI (like Kelp did to PSGI)
		return $self->to;
	}
	else {
		weaken $self;
		my $dest = $self->get_destination;

		return async sub ($scope, $receive, $send) {
			Gears::X->raise('bad PAGI execution chain, not a thunderhorse app')
				unless exists $scope->{thunderhorse};

			my $context = $scope->{thunderhorse}{context};
			$context->set_pagi([$scope, $receive, $send]);

			my $res = $context->res;
			try {
				my $result = $dest->($self, $context, $matched->@*);
				$result = await $result
					if $result isa 'Future';

				if (defined $result && !$res->rendered) {
					# TODO: result should be an array? (code, content_type, content)
					await $res->code(200)->render(html => $result);
				}
			}
			catch ($ex) {
				die $ex unless $ex isa 'Gears::X::HTTP';
				await $res->code($ex->code)->render(text => $ex->message);
			}
		};
	}
}

sub compare ($self, $method, $path)
{
	return undef unless $self->method eq $method;
	return $self->SUPER::compare($path);
}

