package Thunderhorse::Router::Location;

use v5.40;
use Mooish::Base -standard;

use Future::AsyncAwait;
use Gears::X;

extends 'Gears::Router::Location::SigilMatch';

has option 'method' => (
	isa => Str,
);

# TODO: ensure names are unique
has param 'name' => (
	isa => Str,
	lazy => 1,
);

has param 'to' => (
	isa => Str | CodeRef,
);

has param 'order' => (
	isa => Int,
	default => 0,
);

has param 'pagi' => (
	isa => Bool,
	default => false,
);

has param 'controller' => (
	isa => ConsumerOf ['Thunderhorse::Routable'],
);

sub BUILD ($self, $)
{
	Gears::X->raise('controller has no action ' . $self->to)
		unless $self->get_destination;

	# build name eagerly
	$self->name;
}

sub _build_name ($self)
{
	my $method = $self->method // 'ANY';
	my $pattern = $self->pattern;
	my $id = $self->router->get_next_route_id;

	# autogenerated location name should be readable, but unique
	return "_${method}_${pattern}_${id}";
}

sub get_destination ($self)
{
	my $to = $self->to;
	return $to if ref $to eq 'CODE';
	return $self->controller->can($self->to);
}

sub compare ($self, $path, $method)
{
	return undef if $self->has_method && $self->method ne $method;
	return $self->SUPER::compare($path);
}
